INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Acre', 'IFAC');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Alagoas', 'IFAL');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Amapá', 'IFAP');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Amazonas', 'IFAM');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal da Bahia', 'IFBA');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal Baiano', 'IFBAIANO');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Ceará', 'IFCE');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Brasília', 'IFB');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Espírito Santo', 'IFES');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Goiás', 'IFG');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal Goiano', 'IFGOIANO');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Maranhão', 'IFMA');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Mato Grosso', 'IFMT');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Mato Grosso do Sul', 'IFMS');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Minas Gerais', 'IFMG');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Norte de Minas Gerais', 'IFNMG');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Sudeste de Minas Gerais', 'IFSUDESTE-MG');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Sul de Minas Gerais', 'IFSULDEMINAS');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Triângulo Mineiro', 'IFTM');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de São Paulo', 'IFSP');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Paraná', 'IFPR');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Rio de Janeiro', 'IFRJ');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal Fluminense', 'IFF');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Rio Grande do Norte', 'IFRN');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Rio Grande do Sul', 'IFRS');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal Farroupilha', 'IFFarroupilha');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal Sul-rio-grandense', 'IFSUL');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Rondônia', 'IFRO');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Roraima', 'IFRR');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Santa Catarina', 'IFSC');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal Catarinense', 'IFC');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal de Sergipe', 'IFS');
INSERT INTO institutos (nome, sigla) VALUES ('Instituto Federal do Tocantins', 'IFTO');

